# .github/workflows/deploy.yml

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install
        env:
          CI: true

      - name: Build and deploy
        run: |
          npm run build
          git config --global user.name amitnishad
          git config --global user.email amitnishad07052000@gmail.com
          git checkout --orphan gh-pages
          mv build/* .
          rm -r build
          git add .
          git commit -m 'Deploy to GitHub Pages'
          git branch -M gh-pages
          git push -f origin gh-pages
        env:
          CI: true
        deploy:
          provider: pages
          skip-cleanup: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          keep-history: true
          local-dir: .
          target-branch: gh-pages


